name: semantic-release
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - run: yarn add semantic-release -D
      - run: npx semantic-release
